spring:
  application:
    name: insurance-app
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:insuranceapp}
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:jain@2020}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none  # Disable Hibernate DDL since we're using Flyway
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
       
server:
  port: 5000  