package com.example.insurance_app.policies;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class PolicyCreateRequest {
    
    // Policy number will be auto-generated by the system
    
    @NotNull(message = "Policy type is required")
    private Policy.PolicyType type;
    
    @Size(max = 1000, message = "Description cannot exceed 1000 characters")
    private String description;
    
    @NotNull(message = "Coverage amount is required")
    @Positive(message = "Coverage amount must be positive")
    private BigDecimal coverageAmount;
    
    @NotNull(message = "Premium amount is required")
    @Positive(message = "Premium amount must be positive")
    private BigDecimal premiumAmount;
    
    @NotNull(message = "Term years is required")
    @Positive(message = "Term years must be positive")
    private Integer termYears;
    
    @NotNull(message = "Premium frequency is required")
    private Policy.PremiumFrequency premiumFrequency;
}
